// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

type Address struct {
	ID      string
	Userid  string
	Address string
}

type Counter struct {
	ID    string
	Count int64
}

type User struct {
	ID   string
	Name string
}
